# Generated by Django 3.1 on 2020-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200831_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoui',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='todoui',
            name='title',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
